# Generated by Django 3.2.6 on 2021-08-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateWiseCovidDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('state', models.CharField(max_length=250)),
                ('confirmed_indian_national', models.IntegerField()),
                ('confirmed_foreign_national', models.IntegerField()),
                ('cured', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('confirmed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StateWiseTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('state', models.CharField(max_length=250)),
                ('total_samples', models.IntegerField()),
                ('negatives', models.IntegerField()),
                ('positives', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StateWiseTestingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('state', models.CharField(max_length=250)),
                ('total_doses_administrated', models.IntegerField()),
                ('total_sessions_conducted', models.IntegerField()),
                ('total_sites', models.IntegerField()),
                ('first_dose_administrated', models.IntegerField()),
                ('second_dose_administrated', models.IntegerField()),
                ('males', models.IntegerField()),
                ('females', models.IntegerField()),
                ('transgender', models.IntegerField()),
                ('total_covaxin_administrated', models.IntegerField()),
                ('total_covisheild_administrated', models.IntegerField()),
                ('total_sputnik_administrated', models.IntegerField()),
                ('aefi', models.IntegerField()),
                ('age_range_18_45', models.IntegerField()),
                ('age_range_45_60', models.IntegerField()),
                ('age_range_gt_60', models.IntegerField()),
                ('total_individuals_vaccinated', models.IntegerField()),
            ],
        ),
    ]
